#!/bin/bash

# NAME: set-hyper-threading
# PATH: /usr/local/bin
# DESC: Turn Hyper threading off or on.

# DATE: Aug. 5, 2017.

# NOTE: Written Part of testing for Ubuntu answer:
#       https://askubuntu.com/questions/942728/disable-hyper-threading-in-ubuntu/942843#942843

# PARM: 1="0" turn off hyper threading, "1" turn it on.

# sudo grep "" /sys/devices/system/cpu/cpu*/topology/core_id

if [[ $# -ne 1 ]]; then
    echo 'One argument required. 0 to turn off hyper-threading or'
        echo '1 to turn hyper-threading back on'
        exit 1
fi

echo $1 > /sys/devices/system/cpu/cpu12/online
echo $1 > /sys/devices/system/cpu/cpu13/online
echo $1 > /sys/devices/system/cpu/cpu14/online
echo $1 > /sys/devices/system/cpu/cpu15/online
echo $1 > /sys/devices/system/cpu/cpu16/online
echo $1 > /sys/devices/system/cpu/cpu17/online
echo $1 > /sys/devices/system/cpu/cpu18/online
echo $1 > /sys/devices/system/cpu/cpu19/online
echo $1 > /sys/devices/system/cpu/cpu20/online
echo $1 > /sys/devices/system/cpu/cpu21/online
echo $1 > /sys/devices/system/cpu/cpu22/online
echo $1 > /sys/devices/system/cpu/cpu23/online

grep "" /sys/devices/system/cpu/cpu*/topology/core_id

grep -q '^flags.*[[:space:]]ht[[:space:]]' /proc/cpuinfo && \
                echo "Hyper-threading is supported"

grep -E 'model|stepping' /proc/cpuinfo | sort -u

stress --cpu 8 --io 1 --vm 1 --vm-bytes 128M --timeout 10s
